#!/bin/sh

##
# Runit run script for postgresql
#

# workaround for aufs bug from
# https://github.com/docker/docker/issues/783#issuecomment-56013588
mkdir /etc/ssl/private-copy
mv /etc/ssl/private/* /etc/ssl/private-copy/
rm -r /etc/ssl/private
mv /etc/ssl/private-copy /etc/ssl/private
chmod -R 0700 /etc/ssl/private
chown -R postgres /etc/ssl/private

# If the database has been persisted in a volume, it may need
# permissions setting.
chown -R postgres /var/lib/postgresql/ || exit 1

exec /sbin/setuser postgres /usr/lib/postgresql/9.4/bin/postgres \
    -D /var/lib/postgresql/9.4/main \
    -c config_file=/etc/postgresql/9.4/main/postgresql.conf
